name: Report a bug
description: Tell us about a bug or issue you have identified.
title: "Bug: [Short summary of the issue]"

body:
  - type: markdown
    attributes:
      value: |
        ## Guidance

        Please use this template to clearly describe the reported bug. Well-structured reports help us identify and fix issues efficiently.

        If you believe the issue may impact security, anonymity, or user privacy, please avoid posting details publicly and instead use the dedicated [security vulnerability reporting](https://github.com/globaleaks/globaleaks-whistleblowing-software/security/advisories/new) form.

        Before proceeding, please ensure you:
        - Review the [Contributing Guidelines](https://github.com/globaleaks/globaleaks-whistleblowing-software/blob/main/.github/CONTRIBUTING.md)
        - Follow the project [Code of Conduct](https://github.com/globaleaks/globaleaks-whistleblowing-software/blob/stable/CODE_OF_CONDUCT.md)
        - Search [existing bug reports](https://github.com/globaleaks/globaleaks-whistleblowing-software/issues?q=is%3Aissue) to avoid duplicates
        - Attempt to reproduce the issue on [https://try.globaleaks.org](https://try.globaleaks.org)

  - type: textarea
    id: software-version
    attributes:
      label: What version of GlobaLeaks are you using?
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Provide a clear description of the issue, including what you expected to happen, what actually happened, and the steps required to reproduce the bug.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution (optional)
      description: If you have an idea how to fix the issue, please describe it here.
    validations:
      required: false
