name: Feature request
description: Suggest a new feature.
title: "Add/Improve [Specific Feature or Capability]"

body:
  - type: markdown
    attributes:
      value: |
        ## Guidance

        Please use this template to clearly describe your feature request. Well-structured proposals are more likely to be reviewed and considered for the development roadmap.

        Before proceeding, please ensure you:
        - Review the [Contributing Guidelines](https://github.com/globaleaks/globaleaks-whistleblowing-software/blob/main/.github/CONTRIBUTING.md)
        - Follow the project [Code of Conduct](https://github.com/globaleaks/globaleaks-whistleblowing-software/blob/stable/CODE_OF_CONDUCT.md)
        - Search [existing proposals](https://github.com/globaleaks/globaleaks-whistleblowing-software/issues?q=is%3Aissue) to avoid duplicates

  - type: textarea
    id: need
    attributes:
      label: Problem/Need
      description: |
        What problem or user need are you trying to address? In what context does this need arise (e.g., legal, usability, security, user feedback)?
    validations:
      required: true

  - type: textarea
    id: current-situation
    attributes:
      label: Current situation
      description: |
        What are the limitations or pain points with the current implementation?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: |
        Please describe your proposed solution in as much detail as possible and include any relevant workflows, UI suggestions, configurations, or technical ideas.
    validations:
      required: true
